name: Security Scan

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  checkov:
    uses: clouddrove/github-shared-workflows/.github/workflows/checkov.yml@master
    with:
      directory: "."
      continue_on_error: "true"
      skip_check: 'CKV_TF_1'