name: Security Scan

on: 
  pull_request: 
    branches: [master]
    types: [opened, synchronize]

jobs: 
  checkov:
    uses: clouddrove/github-shared-workflows/.github/workflows/checkov.yml@88efd7724e007c8f721a219498be29e0c9ad471b # pinned to latest
    with:
      directory: '.'
      continue_on_error: 'true'
      skip_check: 'CKV_TF_1'