name: Module Test Harness

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@521761c1a5cf68d919980a2ed84b755182aeabfe
    with:
      provider: digitalocean
      working_directory: ./_examples/basic/
  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@521761c1a5cf68d919980a2ed84b755182aeabfe
    with:
      provider: digitalocean
      working_directory: ./_examples/complete/
